image: elixir:1.12.2

stages:
  - build_release
  - push_release


build_release:
  stage: build_release
  dependencies: []
  variables:
    MIX_ENV: prod
    RELEASE_TAR: 1
  script: 
    - apt-get -qq update
    - apt-get install -y libmagic-dev
    - apt-get install -y gcc g++ musl-dev make cmake
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod +x ./mc 

    - rm -rf _build/*/lib/pleroma
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix release

    - RELEASE=$(ls _build/prod/pleroma*.tar.gz | tail -n 1)
    - TARGET_NAME="pleroma-$(date -u +"%Y%m%dT%H%M%S").tar.gz"
    - TARGET="s3/${AWS_BUCKET_NAME}/$MIX_ENV/$TARGET_NAME"
    - LATEST_TARGET="s3/${AWS_BUCKET_NAME}/$MIX_ENV/latest.tar.gz"

    - ./mc alias set s3 https://s3.amazonaws.com ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}
    - ./mc cp $RELEASE ${TARGET}
    - ./mc cp $RELEASE ${LATEST_TARGET}